#!/bin/bash

iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

# iptables -A INPUT -p icmp --icmp-type echo-request -j ACCEPT
# iptables -A OUTPUT -p icmp --icmp-type echo-reply -j ACCEPT
iptables -A OUTPUT -p icmp --icmp-type echo-request -j ACCEPT
iptables -A INPUT -p icmp --icmp-type echo-reply -j ACCEPT

iptables -A INPUT -i enp63s0 -s 192.168.1.0/24 -j ACCEPT
iptables -A OUTPUT -o enp63s0 -s 192.168.1.0/24 -j ACCEPT

iptables -A INPUT -i enp63s0 -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -o enp63s0 -m state --state NEW,ESTABLISHED -j ACCEPT




